contact_links:
  - name: Question
    url: https://github.com/azurenoops/terraform-github-actions/discussions
    about: Please ask questions as a new discussion if others would benefit from seeing the answer
